  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: adminroot
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #空闲链接最大存活时间
      idle-timeout: 1800000
      #最大链接数
      maximum-pool-size: 10
      #自动提交
      auto-commit: true
      #最大存活时间
      max-lifetime: 1800000
      #连接超时时间30秒
      connection-timeout: 3000
      #心跳机制 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 8
        #最大连接阻塞时间
        max-wait: 1000ms
        #最大空闲连接，默认8
        max-idle: 200

  #RabbitMQ
  rabbitmq:
    #服务器
    host: 127.0.0.1
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true



#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.atgao.pay.pojo

logging:
  level:
    com.atgao.seckill.mapper: debug